spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product
    username: product
    password: product
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: product-consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8084

logging:
  level:
    root: info
    com.baedal.product: debug